# Generated by Django 4.1.13 on 2024-05-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0002_alter_invoicelistmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelistmodel',
            name='invoiceNo',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoiceNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoiceApp.invoicelistmodel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
