# Generated by Django 4.1.13 on 2024-05-08 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0004_remove_invoicelistmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelistmodel',
            name='invoiceNo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
